# Use root/example as user/password credentials
version: '3.1'

services:
  # TODO: docker image of the single page application in react
  #web:
    #build: client/.
    #ports:
      #- 3000:3000
  
  api:
    build: server/.
    ports:
      - 8080:8080
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    ports:
      # bind mongod port for external access, for example from robomongo
      - 27017:27017 
    #volumes:
      # map volume to persist mongo db
      #- './server/data/mongodb:/data/db'
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    